name: build

on:
  schedule:
  - cron:  '30 5 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          ./build.sh -

      - name: Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: scripts/*.iso
          scp_target: ${{ secrets.UBUNTU_OP_TARGET }}

      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-op-latest
          path: scripts/ubuntu-op-latest.iso
