name: build-focal

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Initiate Build
        run: |
          cd scripts
          ./build.sh -

      - name: Debug
        run: |
          ls -hl scripts/
