name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Initiate Build
        run: |
          cd scripts
          ./build.sh -
      
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-op-latest
          path: scripts/ubuntu-op-latest.iso
          
      - uses: mdallasanta/ssh-scp-deploy@{version}
        with:
          local: './scripts'                                              
          remote: ${{ secrets.UBUNTU_OP_TARGET }}                                      
          host: ${{secrets.HOST}}                              
          port: ${{secrets.PORT}}                     
          user: ${{secrets.USER}}                        
          password: ${{secrets.PASSWORD}}                        
          key: ${{secrets.KEY}}                                 
          pre_upload: ls -alh

      - name: Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          scp_source: scripts/ubuntu-op-latest.iso
          scp_target: ${{ secrets.UBUNTU_OP_TARGET }}
